git config --global user.name rock
git config --global user.email rock@domain.com
git config --global alias.st status
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.br branch
git config --global core.editor vim
git config --global merge.tool vimdiff
git config --global diff.tool vimdiff
git config --global color.status auto
git config --global color.branch auto
git config --global color.interactive auto
git config --global color.diff auto
