{
 "title": "BJ-Node-Monitor",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "prometheus" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "NodeGroup",
    "label": "NodeGroup",
    "query": "label_values(node_load1{ job=\"node_exporter\"},group)"
   },
   {
    "name": "hosts",
    "label": "hosts",
    "query": "label_values(node_load1{group=~\"$NodeGroup:*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count by(cpu)(node_cpu_seconds_total{group=~\"$NodeGroup\", instance=~\"$hosts:*\",mode=\"system\"}))"
      }
     ]
    },
    {
     "title": "Disk Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\", device=~\"/dev/.*\"})"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
     "format": "s",
     "valueName": "avg",
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}"
      }
     ]
    },
    {
     "title": "Process running num",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_procs_running{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}"
      }
     ]
    },
    {
     "title": "Process Blocked Num",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_procs_blocked{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}"
      }
     ]
    },
    {
     "title": "File descriptor max num",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_filefd_maximum{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}"
      }
     ]
    },
    {
     "title": "Scrape CPU use",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(irate(node_exporter_build_info{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m]))"
      }
     ]
    }
   ]
  },
  { "title": "System Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",mode='user'}[5m])) * 100 / count(count by (cpu)(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",mode='nice'}[5m])) * 100 / count(count by (cpu)(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",mode='system'}[5m])) * 100 / count(count by (cpu)(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",mode='iowait'}[5m])) * 100 / count(count by (cpu)(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",mode='softirq'}[5m])) * 100 / count(count by (cpu)(node_cpu_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}))",
     "legendFormat": "softirq"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}) /  count(count(node_load1{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[2m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} / node_memory_MemTotal_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}) * 100"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\", device!~\"lo|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\", device!~\"lo|cbr[0-9]|veth.*\"}[5m]) > 0",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Free Filesystem Space (Lowest)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{fstype=~\"xfs|ext4|ext3\",group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4|ext3\",group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} - node_memory_MemFree_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} - node_memory_Cached_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} - node_memory_Buffers_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} - node_memory_Slab_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"} + node_memory_Slab_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_vmstat_pswpin{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Swap In"
    },
    {
     "expr": "node_vmstat_pswpout{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}[5m])+ irate(node_disk_written_bytes_total{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}[5m]) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IOPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m]))",
     "legendFormat": "reads per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m]))",
     "legendFormat": "writes per second"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m]))",
     "legendFormat": "io time"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m])) + sum by (instance) (irate(node_disk_writes_completed_total{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\"}[5m]))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Disk await",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(irate(node_disk_write_time_seconds_total{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}[5m])+irate(node_disk_read_time_seconds_total{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}[5m]))/irate(node_disk_io_time_seconds_total{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "File descriptor allocated num",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{group=~\"$NodeGroup:*\",instance=~\"$hosts:*\"}",
     "legendFormat": "node_filefd_allocated"
    }
   ]
  },
  {
   "title": "Node available Filesystem",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",fstype=~\"xfs|ext4|ext3\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Top5  used filesystems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, 100 - (node_filesystem_free_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",fstype=~\"xfs|ext4|ext3\"} / node_filesystem_size_bytes{group=~\"$NodeGroup:*\", instance=~\"$hosts:*\",fstype=~\"xfs|ext4|ext3\"} * 100))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}