apiVersion: v1
kind: Namespace
metadata:
  name: ns-lazywhite
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter-lazywhite
  namespace: ns-lazywhite
  labels:
    app: alpine
spec:
  containers:
    - name: gui3-server
      image: nvidia/cuda
      command: ["sleep", "99999999999"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
