---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: default
data:
  json1: "{key: 100, key2: 200}"
---

apiVersion: v1
kind: Pod
metadata:
  name: t1
  namespace: default
spec:
  containers:
    - name: c1
      image: busybox
      command: ["sleep", "60000"]
      env:
        - name: SPECIAL_KEY
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: json1

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=  # echo -n "admin"|base64
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never

## echo $SECRET_USERNAME ==> admin  # base64 decoded value
