apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-01
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "tensorflow/tensorflow:latest-gpu"
      command: ['sleep', '60000']
  nodeSelector:
    accelerator: nvidia-tesla-p40 # or nvidia-tesla-k80 etc.

