---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-t1
  labels:
    app: gpu-test
spec:
  containers:
    - name: cuda-container
      image: tensorflow/tensorflow:latest-gpu
      ports:
        - containerPort: 8888
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs


---

kind: Service
apiVersion: v1
metadata:
  name: gpu-service
spec:
  selector:
    app: gpu-test
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter1
  namespace: default
spec:
  rules:
  - host: jupyter1.app.local.com
    http:
      paths:
      - backend:
          serviceName: gpu-service
          servicePort: 8888
        path: /
status:
  loadBalancer: {}

